-- 자동차 종류 IN ('세단', 'SUV')
-- 2022년 11월 1일 ~ 2022년 11월 30일까지 대여 가능
-- 30일간 대여 금액이 50 <= X < 200


SELECT CAR_ID, C.CAR_TYPE, ROUND((DAILY_FEE * (100 - DISCOUNT_RATE) / 100 * 30),0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON C.CAR_TYPE = P.CAR_TYPE AND P.DURATION_TYPE = '30일 이상' 
WHERE C.CAR_TYPE IN ('세단', 'SUV') 
AND
CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    WHERE END_DATE > '2022-11-01'
    GROUP BY CAR_ID
    ORDER BY END_DATE DESC
) 
GROUP BY CAR_ID
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;

-- WHERE에 FEE 조건을 두면 오류 / HAVING에 해야함