-- 식품분류별 가장 비싼 식품의 정보 조회하기랑 비슷한 문제
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE (FOOD_TYPE, FAVORITES) IN
        (SELECT FOOD_TYPE, MAX(FAVORITES)
         FROM REST_INFO
         GROUP BY FOOD_TYPE)
ORDER BY FOOD_TYPE DESC;