-- 2021년 가입한 전체 회원들 중 상품을 구매한 회원수와 상품을 구매한 회원의 비율

SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT U.USER_ID) AS PUCHASED_USERS,
ROUND(COUNT(DISTINCT U.USER_ID) / (SELECT COUNT(USER_ID)
                          FROM USER_INFO
                          WHERE YEAR(JOINED) = 2021),1) AS PUCHASED_RATIO
FROM (SELECT * 
      FROM USER_INFO
      WHERE YEAR(JOINED) = 2021) U
INNER JOIN ONLINE_SALE O
ON U.USER_ID = O.USER_ID
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;

/*
SELECT COUNT(USER_ID)
FROM USER_INFO
WHERE YEAR(JOINED) = 2021;
*/