-- 코드를 입력하세요
SELECT O.PRODUCT_ID, PRODUCT_NAME, SUM(AMOUNT)*PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT P INNER JOIN FOOD_ORDER O ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE DATE_FORMAT(PRODUCE_DATE,'%Y-%m') = '2022-05'
GROUP BY O.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, O.PRODUCT_ID;