-- HOUR에 0부터 23까지를 어떻게 나타내지
WITH RECURSIVE CTE AS (
    SELECT 0 AS num
    UNION ALL 
    SELECT num + 1
    FROM CTE
    WHERE num < 23
)

SELECT CTE.num, COUNT(O.ANIMAL_ID) AS COUNT
FROM CTE
LEFT JOIN ANIMAL_OUTS O
ON CTE.num = HOUR(O.DATETIME)
GROUP BY num;


/*SELECT HOUR(DATETIME) AS HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS
GROUP BY HOUR
ORDER BY HOUR;
*/