-- 2021년 출팔된 인문 (출판일 기준 오름차순)
SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE,'%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK
WHERE PUBLISHED_DATE LIKE '2021%' AND CATEGORY = '인문'
ORDER BY PUBLISHED_DATE;
-- TOCHAR(PUBLISHED_DATE, 'YYYY-MM-DD')