-- 죽일까... IFNULL ...

SELECT HISTORY_ID, ROUND(DAILY_FEE *(100 - IFNULL(DISCOUNT_RATE,0))/100 * (DATEDIFF(END_DATE,START_DATE)+1),0) AS FEE 
FROM CAR_RENTAL_COMPANY_CAR C 
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H 
ON C.CAR_ID = H.CAR_ID 
LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON C.CAR_TYPE = P.CAR_TYPE 
AND DURATION_TYPE =
    CASE
       WHEN DATEDIFF(END_DATE,START_DATE)+1 >= 90 THEN '90일 이상'
       WHEN DATEDIFF(END_DATE,START_DATE)+1 >= 30 THEN '30일 이상'
       WHEN DATEDIFF(END_DATE,START_DATE)+1 >= 7 THEN '7일 이상' 
    END
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC;